### ISSUE TITLE
Question about Drawing Pipeline Diagrams

### ISSUE THREAD

**Issue by hi-zgl** [zju3dv/EnvGS#2]
Hello author, thank you for your excellent work. Your pipeline diagram looks gorgeous,  I want to know which software you used to create it. 
![image](https://github.com/user-attachments/assets/6b77bf48-3276-48cf-9931-9d6cf788164f)

**Comment by xbillowy** [comment]
Hi, thank you for your interest!

We use Blender along with the [import ply as verts](https://github.com/TombstoneTumbleweedArt/import-ply-as-verts) plugin to render the scene diagrams in our pipeline.

**Comment by hi-zgl** [comment]
> Hi, thank you for your interest!
> 
> We use Blender along with the [import ply as verts](https://github.com/TombstoneTumbleweedArt/import-ply-as-verts) plugin to render the scene diagrams in our pipeline.

Okay, thank you for your reply. Wishing you happiness every day.
